version: '3'

services:
  db:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

  inventory-command-service:
    build: './inventory-command-service'
    restart: always
    depends_on:
      - db
      - redis

  inventory-query-service:
    build: './inventory-query-service'
    restart: always
    depends_on:
      - db
      - redis

  order-service:
    build: './order-service'
    restart: always
    depends_on:
      - db
      - redis

  http-api-gateway:
    build: './http-api-gateway'
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - redis
      - inventory-command-service
      - inventory-query-service
      - order-service

volumes:
  db-data: {}
